#include "Vroom/Render/StructuredBuffer.h"
#include <cstring>

#include "Vroom/Core/Assert.h"

using namespace vrm::render;

void StructuredBuffer::_setAttributeData(std::span<std::byte const>   data,
                                         const SSBO430Layout::Attrib& attribute,
                                         size_t arrayIndex)
{
  VRM_ASSERT_MSG(m_arraySize > arrayIndex, "Array index is out of bounds");
  VRM_ASSERT_MSG(
    attribute.getAlignment() + attribute.getSize() <= m_layout.getRawSize(),
    "Attribute is out of element bounds. Was this attribute generated by the "
    "layout of this structured buffer?");

  const size_t location =
    arrayIndex * m_layout.getAlignedSize() + attribute.getAlignment();

  std::memcpy(&m_data[location], data.data(), data.size());
}
